### ISSUE TITLE
Can`t work anymore...

### ISSUE THREAD

**Issue by philboycn** [PeteLawrence/homebridge-people#82] opened 2017-09-04 01:41 UTC
Hello..Pls help me with this issue..

It worked fine until one day I updated a lot of plugins include homebridge-people and homebridge itself.
Now Anyone and Noone sensor can not trigger itself.
it only triggered when i open home app on my iphone.

Pls help!  Thanks!

**Comment by sohnkarlsruhe** [comment] 2017-09-05 10:50
same problem here

**Comment by philboycn** [comment] 2017-09-05 13:59
solved with downgrade the homebridge version.
homebridge 0.4.25 works fine.

**Comment by Bankaifan** [comment] 2017-09-06 07:49
Same problem over here

This are my Plugins

pi@raspberrypi:~ $ list-versions 
###############################################
Plugin Versionen:
/usr/local/lib
├── homebridge@0.4.27
├── homebridge-fritz@0.5.6
├── homebridge-gpio@0.0.4
├── homebridge-harmonyhub@0.2.0
├── homebridge-hue@0.5.27
├── homebridge-people@0.6.1
├── homebridge-philipstv@0.3.81
├── homebridge-rcswitch-gpiomem@1.1.4
├── homebridge-suncalc@0.0.1
├── homebridge-telldus@0.0.9
├── homebridge-xiaomi-mi-robot-vacuum@1.1.0
├── miio@0.13.0
├── n@2.1.8
├── npm@5.4.0
├── npm-check@5.4.5
├── npm-check-updates@2.12.1
├── requests@0.2.2
├── undefined@0.1.0
└── vim@0.1.0

NPM-Version
5.4.0
Node-Version
v8.4.0

**Comment by Bankaifan** [comment] 2017-09-06 08:50
I tried downgrading to 0.4.25, did not change anything. The status of "Anyone" or "No-one" only changes, if i open one of the apps.

**Comment by deanlyoung** [comment] 2017-09-08 17:04
@prmx promising if replicable! Any way you can do a pull request?

**Comment by prmx** [comment] 2017-09-11 10:29
@deanlyoung yeap, I can do PR today at night. One remark about this fix, homebridge will recreate those sensors at homekit (because of different sensor types) and all automations that was created for them will be lost, you should create them again.

**Comment by benzman81** [comment] 2017-09-11 10:41
IMHO isn't using a MotionSensor for Occupancy just a hack around a homekit issue? Since this plugin detects occupancy it should use OccupancySensor and wait for fixes in homekit.

**Comment by prmx** [comment] 2017-09-11 11:17
Agree, maybe we could wait few days for iOS11 and tvOS11 with hope that apple will fix it :)
but at tvOS11@beta and iOS10@latest it still reproducible for me

**Comment by deanlyoung** [comment] 2017-09-11 18:17
@prmx @benzman81 good point, but I thought this was an issue with homebridge and not HomeKit, since the issue appears on homebridge@0.4.27

**Comment by stephanroslen** [comment] 2017-09-20 16:57
Fixed with https://github.com/PeteLawrence/homebridge-people/pull/83

**Comment by PeteLawrence** [comment] 2017-10-20 18:45
I've just published 0.6.2 that should fix this.  Thanks to @stephanroslen for the PR.

**Closed by PeteLawrence** 2017-10-20 18:45 UTC
